spring.application.name=app
server.port=8080

spring.datasource.url=jdbc:h2:file:./data/appdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.out-of-order=true

security.default.username=ivan.ivanov@epidem.ru
security.default.user-id=ca078170-df17-48f8-bca4-d89000a6e87f
security.default.full-name=\u0418\u0432\u0430\u043d\u043e\u0432 \u0418\u0432\u0430\u043d \u0418\u0432\u0430\u043d\u043e\u0432\u0438\u0447
security.jwt.secret=dGhpcy1pcy1hLXNlY3VyZS1hbmQtbG9uZy1zZWNyZXQta2V5LWZvci1qc29uLXdlYi10b2tlbi1zaWduYXR1cmUtMjU2Yml0cw==
