-- Seed default documents for parallel frontend and backend integration tests
INSERT INTO documents (id, title, file_path, metadata) VALUES (1, 'Бюджетный план образовательного центра на 2026 год', '/files/budget.pdf', '{"description":"Смета расходов и financial планирование образовательного центра ФБУН ЦНИИ Эпидемиологии.","doc_type":"Regulations","specialty":"Other","edu_level":"Residency","category_id":"edu_budget_finance","tags":["бюджет","финансы","нормативные акты"],"version":1,"fileSize":350000,"fileType":"application/pdf","updatedAt":"2026-08-01T10:00:00Z","updatedBy":"economist.ivanov@epidem.ru"}');

INSERT INTO documents (id, title, file_path, metadata) VALUES (2, 'ФГОС ВО по специальности Эпидемиология', '/files/fgos.pdf', '{"description":"Федеральный государственный образовательный стандарт высшего образования по направлению Эпидемиология (ординатура). Обязателен для всех учебных программ кафедры.","doc_type":"Regulations","specialty":"Epidemiology","edu_level":"Residency","category_id":"edu_center_root","tags":["ординатура","нормативные акты","ФГОС"],"version":3,"fileSize":245000,"fileType":"application/pdf","updatedAt":"2026-08-01T10:00:00Z","updatedBy":"ivan.ivanov@epidem.ru"}');

INSERT INTO documents (id, title, file_path, metadata) VALUES (3, 'Шаблон протокола ГЭК для ГИА', '/files/protocol_template.docx', '{"description":"Официальный шаблон протокола заседания государственной экзаменационной комиссии. Применяется для оформления результатов ГИА.","doc_type":"Forms/Templates","specialty":"Other","edu_level":"Residency","category_id":"edu_academic_reports","tags":["шаблоны","ГЭК","ГИА","ординатура"],"version":1,"fileSize":125000,"fileType":"application/vnd.openxmlformats-officedocument.wordprocessingml.document","updatedAt":"2026-07-15T14:30:00Z","updatedBy":"elena.petrova@epidem.ru"}');

INSERT INTO documents (id, title, file_path, metadata) VALUES (4, 'Методические рекомендации по детским инфекционным болезням', '/files/guidelines.pdf', '{"description":"Методические материалы по специальности Педиатрия. Включает клинические кейсы, планы занятий и перечень компетенций ФГОС.","doc_type":"Guidelines","specialty":"Pediatrics","edu_level":"Additional Professional Education","category_id":"edu_center_root","tags":["педиатрия","инструкции","рекомендации"],"version":2,"fileSize":412000,"fileType":"application/pdf","updatedAt":"2026-07-28T09:15:00Z","updatedBy":"ivan.ivanov@epidem.ru"}');

INSERT INTO documents (id, title, file_path, metadata) VALUES (5, 'Вопросы к кандидатскому экзамену по специальности Инфекционные болезни', '/files/exam_questions.pdf', '{"description":"Перечень теоретических вопросов и практических заданий для подготовки к кандидатскому экзамену по инфекционным болезням аспирантов.","doc_type":"Protocols","specialty":"Infectious Diseases","edu_level":"Postgraduate","category_id":"edu_academic_reports","tags":["аспирантура","вопросы к экзаменам","аттестация"],"version":4,"fileSize":189000,"fileType":"application/pdf","updatedAt":"2026-08-02T16:45:00Z","updatedBy":"sergey.smirnov@epidem.ru"}');

INSERT INTO documents (id, title, file_path, metadata) VALUES (6, 'Регламент интеграции учебных планов в СЭД ФБУН', '/files/integration_regulations.pdf', '{"description":"Регламент и пошаговые инструкции по выгрузке данных в СЭД образовательного центра ФБУН ЦНИИ Эпидемиологии Роспотребнадзора.","doc_type":"Regulations","specialty":"Other","edu_level":"Additional Professional Education","category_id":"edu_staff_workload","tags":["ФБУН","инструкции","регламент"],"version":2,"fileSize":310000,"fileType":"application/pdf","updatedAt":"2026-06-20T11:00:00Z","updatedBy":"ivan.ivanov@epidem.ru"}');
